In [1]:
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from sklearn import svm

In [2]:
# read data from csv
def read_data():
    train = pd.read_csv('../input/train_features')
    test = pd.read_csv('../input/test_features')
    label = pd.read_csv('../input/train_label',header=None)
    return train,test,label

In [3]:
clf = svm.LinearSVR()

In [4]:
X_train,X_test,y = read_data()
from sklearn.model_selection import cross_val_score
print(cross_val_score(clf, X_train, y))

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[ 0.56733689  0.6444797   0.64652417]


In [6]:
X_train,X_test,y = read_data()
from sklearn.model_selection import cross_val_score
print(cross_val_score(clf, X_train, np.array(y),cv=5))

[ 0.4432034  -1.31568443  0.67160008  0.38073481  0.47144987]


In [7]:
X_train,X_test,y = read_data()
from sklearn.model_selection import cross_val_score
print(cross_val_score(clf, X_train, np.array(y),cv=5,scoring='neg_mean_squared_error'))

[-0.04368994 -0.07247724 -0.04659942 -0.11943212 -0.0635702 ]


In [8]:
from sklearn.linear_model import Lasso
model_lasso = Lasso()
print(cross_val_score(model_lasso, X_train, np.array(y),cv=5,scoring='neg_mean_squared_error'))

[-0.06132573 -0.07543576 -0.07389983 -0.07244177 -0.07707467]


In [9]:
import xgboost as xgb
dtrain = xgb.DMatrix(X_train, label = y)
#params = {"max_depth":2, "eta":0.1}
model_xgb = xgb.XGBRegressor(n_estimators=360, max_depth=2, learning_rate=0.1)
print(cross_val_score(model_xgb, X_train, np.array(y),cv=5,scoring='neg_mean_squared_error'))

[-0.01280587 -0.01984765 -0.01582305 -0.01441555 -0.01554301]


In [10]:
clf.fit(X_train,y)

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)

In [11]:
clf.predict(X_test)

array([ 11.82538481,  11.5948868 ,  11.98727368, ...,  11.90842879,
        11.53238814,  12.20577423])

In [12]:
x = pd.DataFrame(clf.predict(X_test))

In [15]:
id_test = pd.read_csv('../input/test_id',header=None)

In [16]:
id_test

0
0     1461
1     1462
2     1463
3     1464
4     1465
5     1466
6     1467
7     1468
8     1469
9     1470
10    1471
11    1472
12    1473
13    1474
14    1475
15    1476
16    1477
17    1478
18    1479
19    1480
20    1481
21    1482
22    1483
23    1484
24    1485
25    1486
26    1487
27    1488
28    1489
29    1490
...    ...
1429  2890
1430  2891
1431  2892
1432  2893
1433  2894
1434  2895
1435  2896
1436  2897
1437  2898
1438  2899
1439  2900
1440  2901
1441  2902
1442  2903
1443  2904
1444  2905
1445  2906
1446  2907
1447  2908
1448  2909
1449  2910
1450  2911
1451  2912
1452  2913
1453  2914
1454  2915
1455  2916
1456  2917
1457  2918
1458  2919

[1459 rows x 1 columns]

In [17]:
x

0
0     11.825385
1     11.594887
2     11.987274
3     12.044098
4     11.895993
5     11.910962
6     11.919049
7     11.867444
8     11.864198
9     11.666286
10    11.966328
11    11.607705
12    11.573456
13    11.789886
14    11.526352
15    12.364688
16    12.277987
17    12.262165
18    12.178546
19    12.513396
20    12.334668
21    12.016416
22    11.866803
23    11.932768
24    11.968705
25    11.983982
26    12.410671
27    12.250481
28    12.040137
29    12.009682
...         ...
1429  11.283343
1430  11.605312
1431  10.959716
1432  11.195302
1433  10.983302
1434  12.051968
1435  12.093805
1436  11.909471
1437  11.847877
1438  11.950443
1439  11.793312
1440  11.689232
1441  11.910852
1442  12.280473
1443  12.292638
1444  11.226024
1445  12.184092
1446  11.629770
1447  11.721775
1448  12.021979
1449  11.214123
1450  11.524362
1451  11.708626
1452  11.551673
1453  11.294867
1454  11.277453
1455  11.573020
1456  11.908429
1457  11.532388
1458  12.205774

[1459 rows x 1 columns]

In [18]:
result = pd.concat(x,id_test)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [19]:
result = x.join(id_test)

ValueError: columns overlap but no suffix specified: RangeIndex(start=0, stop=1, step=1)

In [20]:
result['test_id']=id_test

NameError: name 'result' is not defined

In [25]:
result = pd.DataFrame({"test_id":id_test},index=xrange(1459))

TypeError: 'numpy.int64' object is not iterable

In [33]:
reslut=pd.DataFrame({'test_id':id_test[:,0],'price':x[:,0]},index = id_test.columns)

TypeError: unhashable type

In [31]:
reslut

price  test_id
0  11.825385     1461

In [35]:
pre_val = pd.DataFrame(clf.predict(X_test))

In [36]:
pre_val

0
0     11.825385
1     11.594887
2     11.987274
3     12.044098
4     11.895993
5     11.910962
6     11.919049
7     11.867444
8     11.864198
9     11.666286
10    11.966328
11    11.607705
12    11.573456
13    11.789886
14    11.526352
15    12.364688
16    12.277987
17    12.262165
18    12.178546
19    12.513396
20    12.334668
21    12.016416
22    11.866803
23    11.932768
24    11.968705
25    11.983982
26    12.410671
27    12.250481
28    12.040137
29    12.009682
...         ...
1429  11.283343
1430  11.605312
1431  10.959716
1432  11.195302
1433  10.983302
1434  12.051968
1435  12.093805
1436  11.909471
1437  11.847877
1438  11.950443
1439  11.793312
1440  11.689232
1441  11.910852
1442  12.280473
1443  12.292638
1444  11.226024
1445  12.184092
1446  11.629770
1447  11.721775
1448  12.021979
1449  11.214123
1450  11.524362
1451  11.708626
1452  11.551673
1453  11.294867
1454  11.277453
1455  11.573020
1456  11.908429
1457  11.532388
1458  12.205774

[1459 rows x 1 columns]

In [37]:
pre_val[0]

0       11.825385
1       11.594887
2       11.987274
3       12.044098
4       11.895993
5       11.910962
6       11.919049
7       11.867444
8       11.864198
9       11.666286
10      11.966328
11      11.607705
12      11.573456
13      11.789886
14      11.526352
15      12.364688
16      12.277987
17      12.262165
18      12.178546
19      12.513396
20      12.334668
21      12.016416
22      11.866803
23      11.932768
24      11.968705
25      11.983982
26      12.410671
27      12.250481
28      12.040137
29      12.009682
          ...    
1429    11.283343
1430    11.605312
1431    10.959716
1432    11.195302
1433    10.983302
1434    12.051968
1435    12.093805
1436    11.909471
1437    11.847877
1438    11.950443
1439    11.793312
1440    11.689232
1441    11.910852
1442    12.280473
1443    12.292638
1444    11.226024
1445    12.184092
1446    11.629770
1447    11.721775
1448    12.021979
1449    11.214123
1450    11.524362
1451    11.708626
1452    11.551673
1453    11

In [38]:
id_test[0]

0       1461
1       1462
2       1463
3       1464
4       1465
5       1466
6       1467
7       1468
8       1469
9       1470
10      1471
11      1472
12      1473
13      1474
14      1475
15      1476
16      1477
17      1478
18      1479
19      1480
20      1481
21      1482
22      1483
23      1484
24      1485
25      1486
26      1487
27      1488
28      1489
29      1490
        ... 
1429    2890
1430    2891
1431    2892
1432    2893
1433    2894
1434    2895
1435    2896
1436    2897
1437    2898
1438    2899
1439    2900
1440    2901
1441    2902
1442    2903
1443    2904
1444    2905
1445    2906
1446    2907
1447    2908
1448    2909
1449    2910
1450    2911
1451    2912
1452    2913
1453    2914
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: 0, dtype: int64

In [39]:
res = pd.DataFrame()

In [40]:
res['price']=pre_val[0]

In [44]:
res['test_id']=id_test[0]

In [45]:
res

price  test_id
0     11.825385     1461
1     11.594887     1462
2     11.987274     1463
3     12.044098     1464
4     11.895993     1465
5     11.910962     1466
6     11.919049     1467
7     11.867444     1468
8     11.864198     1469
9     11.666286     1470
10    11.966328     1471
11    11.607705     1472
12    11.573456     1473
13    11.789886     1474
14    11.526352     1475
15    12.364688     1476
16    12.277987     1477
17    12.262165     1478
18    12.178546     1479
19    12.513396     1480
20    12.334668     1481
21    12.016416     1482
22    11.866803     1483
23    11.932768     1484
24    11.968705     1485
25    11.983982     1486
26    12.410671     1487
27    12.250481     1488
28    12.040137     1489
29    12.009682     1490
...         ...      ...
1429  11.283343     2890
1430  11.605312     2891
1431  10.959716     2892
1432  11.195302     2893
1433  10.983302     2894
1434  12.051968     2895
1435  12.093805     2896
1436  11.909471     2897
1437  11.847877     2898
1438  11.950443     2899
1439  11.793312     2900
1440  11.689232     2901
1441  11.910852     2902
1442  12.280473     2903
1443  12.292638     2904
1444  11.226024     2905
1445  12.184092     2906
1446  11.629770     2907
1447  11.721775     2908
1448  12.021979     2909
1449  11.214123     2910
1450  11.524362     2911
1451  11.708626     2912
1452  11.551673     2913
1453  11.294867     2914
1454  11.277453     2915
1455  11.573020     2916
1456  11.908429     2917
1457  11.532388     2918
1458  12.205774     2919

[1459 rows x 2 columns]

In [46]:
clf

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)

In [49]:
clf.fit(X_train,y)

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)

In [54]:
clf.predict([.04452243772,4.39444915467,9.36074117264,5,6,1961,1961,0.0,6.15060276845,4.97673374242,5.60211882088,6.7833252006,6.79905586206,0.0,0.0,6.79905586206,0.0,0.0,1,0,2,0.69314718056,5,0,1961.0,1.0,730.0,4.94875989038,0.0,0.0,0.0,4.7957905456,0.0,0.0,6,2010,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0])

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 11.94603957])

In [55]:
label = pd.read_csv('../input/train_label',header=None)

In [56]:
label.head(1)

0
0  12.247699